[WIP] Add device availability
icebreaker-science/frontend pull request #31
Opened 2020-09-19 11:55 UTC by michael-kamel

- Still needs to be coupled with the network nodes and the contact form(maybe can be opened from somewhere else as well?)
- We probably need a standard way for displaying when resources are not found and when errors occur
- I added ngx-bootstrap

2020-09-25 17:39 UTC, chaoran-chen requested changes
Could you please add links to the wiki pages from the device overview/search page?

2020-09-25 18:16 UTC, michael-kamel commented
> Could you please add links to the wiki pages from the device overview/search page?

Should I keep the query param for now as well?

2020-09-25 20:40 UTC, chaoran-chen commented
I think that path param would be better, i.e., `/wiki-page/{id}`.

2020-09-26 22:27 UTC, chaoran-chen approved these changes

2020-09-26 22:28 UTC, merged