add logo-container on homepage and carl-zeiss-logo
icebreaker-science/frontend pull request #82
Opened 2020-11-18 12:26 UTC by BJRWolf

closes #67

2020-11-18 12:28 UTC, BJRWolf commented
forgot to link the page, update in a few minutes.

2020-11-18 21:31 UTC, chaoran-chen requested changes
I have the feeling that it is not very clear what the role of CZS is and why their logo is on our page. What do you think? Maybe add a "Partner" header?

2020-11-19 16:25 UTC, BJRWolf commented
yeah I think its better with a headline. I also rebased  the branch

2020-11-20 07:42 UTC, chaoran-chen approved these changes

2020-11-20 07:42 UTC, merged